/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddTHIStoCOURSE.java
 *
 * Created on Apr 2, 2012, 5:23:26 PM
 */

package cpsc330_betterbanner;

/**
 *
 * @author Isaac Erickson
 */
public class AddTHIStoCOURSE extends javax.swing.JFrame {

    /** Creates new form AddTHIStoCOURSE */
    public AddTHIStoCOURSE() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sumbit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("-");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("-");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("-");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("-");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("-");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Add Courses by CRN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean fail1 = false;
        boolean fail2 = false;
        boolean fail3 = false;
        boolean fail4 = false;
        boolean fail5 = false;
        boolean fail6 = false;

        if(!jTextField1.getText().equals("")){
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField1.getText() + "';").equals(jTextField1.getText())){
                fail1 = true;
                jLabel1.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" +
                jTextField1.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" +
                jTextField1.getText() + "';")) >= 20){
                fail1 = true;
                jLabel1.setText("FULL");
            }               
        }
        
        if(!jTextField2.getText().equals("")){
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField2.getText() + "';").equals(jTextField2.getText())){
                fail2 = true;
                jLabel2.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" +
                jTextField2.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" +
                jTextField2.getText() + "';")) >= 20){
                fail2 = true;
                jLabel2.setText("FULL");
            }        
        }
        
        if(!jTextField3.getText().equals("")){
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField3.getText() + "';").equals(jTextField3.getText())){
                fail3 = true;
                jLabel3.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" +
                jTextField3.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" +
                jTextField3.getText() + "';")) >= 20){
                fail3 = true;
                jLabel3.setText("FULL");
            }         
        }
        
        if(!jTextField4.getText().equals("")){
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField4.getText() + "';").equals(jTextField4.getText())){
                fail4 = true;
                jLabel4.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" +
                jTextField4.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" +
                jTextField4.getText() + "';")) >= 20){
                fail4 = true;
                jLabel4.setText("FULL");
            }    
        }
        
        if(!jTextField5.getText().equals("")){ 
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField5.getText() + "';").equals(jTextField5.getText())){
                fail5 = true;
                jLabel5.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" + 
                jTextField5.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" + 
                jTextField5.getText() + "';")) >= 20){
                fail5 = true;
                jLabel5.setText("FULL");            
            }    
        }
        
        if(!jTextField6.getText().equals("")){ 
            if(!Version.RunSearch
                ("SELECT CRN FROM course WHERE CRN= '" + 
                jTextField6.getText() + "';").equals(jTextField6.getText())){
                fail6 = true;
                jLabel6.setText("ERROR");
            }
            if(!Version.RunSearch("SELECT COUNT(*) FROM enrole WHERE UID= '" +
                Main.Start.getUID() + "' AND CRN= '" +
                jTextField6.getText() + "';").equals("0") ||
                Integer.valueOf(Version.RunSearch
                ("SELECT COUNT(*) FROM enrole WHERE CRN= '" +
                jTextField6.getText() + "';")) >= 20){
                fail6 = true;
                jLabel6.setText("FULL");
            }
        }

        
        
        









        
        

        if(!fail1){
            if(!jTextField1.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField1.getText())+ ");");
        }
        if(!fail2){
            if(!jTextField2.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField2.getText())+ ");");
        }
        if(!fail3){
            if(!jTextField3.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField3.getText())+ ");");
        }
        if(!fail4){
            if(!jTextField4.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField4.getText())+ ");");
        }
        if(!fail5){
            if(!jTextField5.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField5.getText())+ ");");
        }
        if(!fail6){
            if(!jTextField6.getText().equals(""))
                Version.RunInsert("INSERT INTO enrole VALUES (" +
                    Main.Start.getUID() +", "+
                    Integer.valueOf(jTextField6.getText())+ ");");
        }
        


        if(!fail1 && !fail2 && !fail3 && !fail4 && !fail5 && !fail6){
            this.setVisible(false);
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTHIStoCOURSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
